server:
  name: "sagooiot-example"
  addr: ":8198" # 服务于服务监听地址，格式为: ":port"，支持tcp、udp两种网络协议
  netType: "mqtt" # 网关系统类型，tcp,mqtt，这个是指这个网关处理设备端的是mqtt协议还是 tcp协议
  duration: 20 # 网关服务心跳间隔，单位秒
  productKey: "sagoo-snmp202406"   # 网关产品标识，用于区分不同的网关产品
  deviceKey: "snmp20240605"   # 网关实例标识，用于区分不同的网关实例，每个部署的网关实例必须唯一，用于在平台上添加这个网关设备标识
  deviceName: "sagoo-snmp网关系统"   # 网关系统名称
  description: "SNMP服务网关系统"   # 网关系统描述
  deviceType: "snmp"   # 网关系统类型
  manufacturer: "sagoo.dn"   # 网关系统厂商
  version: "1.0.0"  # 网关系统版本
  deviceConfigFile: "config/devices" # 设备配置文件路径

# SNMP Server.
trapServer:
  address: 0.0.0.0:162
  version: 2c
  community: public

  handle:
    - oid: .
      log:
        path: /path/to/logfile
    - oid: ifAdminStatus
      drop: true
    - oid: ifOperStatus
      drop: true
      cmd:
        command: /path/to/command
    - oid: .
      fwd:
        address: 10.10.10.10:162
        version: '1'
        community: public

# MQTT Server.
mqtt:
  address: 127.0.0.1:1883
  clientId: sagoo-modbus-gateway202405    # 客户端id，注意：MQTT使用过种客户端id不能重复
  keepAliveDuration: 30 # mqtt心跳超时时间，单位秒
  qos: 1 # 服务质量
  auth:
    userName: "xinjy"
    passWord: "123456"
  clientCertificate: # 客户端证书配置
    ca: "" # 如果采用证书双向认证，必须填 Client 连接Hub的CA证书路径
    key: "" # 如果采用证书双向认证，必须填 Client 连接Hub的客户端私钥路径
    cert: "" # 如果采用证书双向认证，必须填 Client 连接Hub的客户端公钥路径

logger:
  path:                  "log/"           # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file:                  "{Y-m-d}.log"         # 日志文件格式。默认为"{Y-m-d}.log"
  prefix:                ""                    # 日志内容输出前缀。默认为空
  level:                 "all"                 # 日志输出级别:all > debug > info > warn > error 生成环境建议使用info
  timeFormat:            "2006-01-02T15:04:05" # 自定义日志输出的时间格式，使用Golang标准的时间格式配置
  ctxKeys:               []                    # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
  header:                true                  # 是否打印日志的头信息。默认true
  stdout:                true                  # 日志是否同时输出到终端。默认true